# Generated by Django 5.1.4 on 2024-12-11 19:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_orderitem_order_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='Product_Category',
        ),
    ]
