# Generated by Django 5.1.4 on 2024-12-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_order_customer_customer_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer_address',
            options={'verbose_name_plural': 'Customer Addresses'},
        ),
        migrations.AddField(
            model_name='customer_address',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
