# Generated by Django 5.1.4 on 2024-12-12 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='Product_Rating',
        ),
    ]
